# Generated by Django 6.1 on 2026-08-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Relationship shown under the name, e.g. "Mother of a Baby"', max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='1 to 5 stars, half-star steps allowed (e.g. 4.5)', max_digits=2),
        ),
    ]
