# Generated by Django 5.2.17 on 2026-08-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('Classrooms', 'Classrooms'), ('Playground', 'Playground'), ('Events', 'Events')], default='Events', max_length=50),
        ),
    ]
